## 应用名称
#spring.application.name=rabbitmq
## 应用服务 WEB 访问端口
#server.port=8001
#
#spring.rabbitmq.host=haproxy.dev.tuboshi.co
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=tbs
#spring.rabbitmq.password=TUTUmaifang
#
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=
#spring.datasource.username=root
#spring.datasource.password=123456
spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: haproxy.dev.tuboshi.co
    port: 5672
    username: tbs
    password: TUTUmaifang
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/my_table
    driver-class-name: com.mysql.jdbc.Driver
    password: 12345678
server:
  port: 8001
